[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  VITE_SUPABASE_URL = "https://ujqehcpglfhnytzsyedp.supabase.co"
  VITE_SUPABASE_ANON_KEY = "sb_publishable_wt_Muu3dmb0GjulWMDYpqg_NKRYqKNE"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
