-- Base de Datos para Centralización de Asistencia y Nóminas (Supabase / Postgres)

-- 1. Catálogo de Sedes
CREATE TABLE IF NOT EXISTS sedes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Inserción de sedes iniciales detectadas en los archivos
INSERT INTO sedes (nombre) VALUES 
('COMAS'),
('ATE'),
('SAN ISIDRO'),
('JOCKEY PLAZA'),
('REMOTO')
ON CONFLICT (nombre) DO NOTHING;

-- 2. Catálogo de Campañas
CREATE TABLE IF NOT EXISTS campanas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL UNIQUE,
    segmento VARCHAR(100),
    supervisor VARCHAR(150),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Inserción de campañas iniciales
INSERT INTO campanas (nombre, segmento, supervisor) VALUES
('CONTACTADOS', 'CLARO PERU RETENCIONES', 'OSCAR ALFREDO URQUIAGA CANO'),
('RETENCIONES INBOUND', 'CLARO PERU RETENCIONES', 'SARA GABRIELA BALVIN GALINDO'),
('CLARO POSTPAGO', 'CLARO PERU', 'ASTRID SOPHIA EYZAGUIRRE DE FREITAS'),
('POSTPAGO', 'CLARO CHILE', 'FERNANDO NOE OYARCE RAMIREZ'),
('UPGRADE', 'CLARO PERU OUT', 'JAMIL DALI ESTRELLA CARHUAMACA'),
('MIGRACIONES ESPECIALES - OUT', 'CLARO PERU OUT', 'ROBERTO ANGEL MORALES VASQUEZ'),
('RENOVACIONES ESPECIALES - WSP', 'CLARO PERU OUT', 'GERALDINE MILAGROS TACURI HUERTAS'),
('VTR', 'CLARO CHILE', 'PEDRO FLORES'),
('RETENCIONES CHILE', 'CLARO CHILE', 'PEDRO FLORES'),
('CLARO PREPAGO', 'CLARO PERU', 'JESUS NAVARRO'),
('CLARO PREMIUM', 'CLARO PERU', 'JESUS NAVARRO'),
('CLARO ROAMING', 'CLARO PERU', 'JESUS NAVARRO')
ON CONFLICT (nombre) DO NOTHING;

-- 3. Catálogo de Reclutadores
CREATE TABLE IF NOT EXISTS reclutadores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_completo VARCHAR(200) NOT NULL UNIQUE,
    activo BOOLEAN DEFAULT TRUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Inserción de reclutadores iniciales
INSERT INTO reclutadores (nombre_completo) VALUES
('Jimenez Patiño Milagros Alexandra'),
('Medina Huari Aldo Manuel'),
('Bustamante Castro Angie Karina'),
('Alvarado Vilchez Matias Sebastian'),
('Flores Toribio Adelly Milena'),
('Benites Aquije Mitchell Maria Fernanda')
ON CONFLICT (nombre_completo) DO NOTHING;

-- 4. Catálogo de Formadores (Trainers)
CREATE TABLE IF NOT EXISTS formadores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento VARCHAR(20) NOT NULL UNIQUE,
    nombre_completo VARCHAR(200) NOT NULL,
    sede VARCHAR(100),
    segmento VARCHAR(150),
    subcampana VARCHAR(150),
    cargo_contractual VARCHAR(150),
    cargo_funcional VARCHAR(150),
    estado VARCHAR(50) DEFAULT 'Activo' CONSTRAINT chk_estado_formador CHECK (estado IN ('Activo', 'Cese')),
    fecha_inicio DATE,
    fecha_cese DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Inserción de formadores iniciales
INSERT INTO formadores (documento, nombre_completo, sede, segmento, subcampana, cargo_contractual, cargo_funcional, estado, fecha_inicio, fecha_cese) VALUES
('41364861', 'CARRASCO MONZON LUZ VANESSA', 'SAN ISIDRO', 'CLARO PERU RETENCIONES', 'CONTACTADOS', 'JEFE DE CAPACITACION', 'JEFATURA', 'Cese', '2025-01-01', '2026-01-01'),
('77276690', 'MONTOYA AGUIRRE SANTIAGO JESÚS', 'COMAS', 'CLARO PERU RETENCIONES', 'CONTACTADOS', 'COORDINADOR DE CAPACITACION', 'COORDINADOR', 'Cese', '2025-01-01', '2026-01-01'),
('40691398', 'SARANGO MORENO ESTRELLITA MARISOL', 'SAN ISIDRO', 'CLARO PERU RETENCIONES', 'RETENCIONES INBOUND', 'JEFATURA', 'JEFATURA', 'Activo', '2025-12-01', NULL),
('43614771', 'CAVERO MONTES SANDRA', 'JOCKEY PLAZA', 'CLARO PERU', 'CLARO POSTPAGO', 'SUPERVISOR DE CAPACITACION', 'SUPERVISOR', 'Activo', '2025-09-23', NULL),
('43306342', 'SERNAQUE NEIRA ROBERTO LUIS', 'COMAS', 'CLARO PERU RETENCIONES', 'CONTACTADOS', 'SUPERVISOR DE CAPACITACION', 'SUPERVISOR', 'Activo', '2026-01-01', NULL),
('45800905', 'RIVAS ZEVALLOS LUIS CARLO', 'SAN ISIDRO', 'CLARO PERU RETENCIONES', 'RETENCIONES INBOUND', 'SUPERVISOR DE CAPACITACION', 'SUPERVISOR', 'Activo', '2025-11-21', NULL),
('45322864', 'RUIZ CHICOMA DE CHUMAN CINTHIA PAOLA DEL MILAGRO', 'COMAS', 'CLARO PERU RETENCIONES', 'CONTACTADOS', 'FORMADOR', 'FORMADOR', 'Activo', '2025-01-01', NULL),
('45531674', 'SALVADOR DE PAZ JHOJAN CHRISTIAN', 'COMAS', 'CLARO PERU RETENCIONES', 'CONTACTADOS', 'FORMADOR', 'TEAM LEADER', 'Activo', '2025-01-01', NULL),
('46545223', 'YEPEZ MONTERO EDDY JEAN FRANCO', 'COMAS', 'CLARO PERU RETENCIONES', 'CONTACTADOS', 'FORMADOR', 'FORMADOR', 'Cese', '2025-01-01', '2024-12-15')
ON CONFLICT (documento) DO NOTHING;

-- 5. Catálogo de Motivos de Baja
CREATE TABLE IF NOT EXISTS motivos_baja (
    motivo VARCHAR(100) PRIMARY KEY,
    siglas VARCHAR(20),
    descripcion TEXT
);

-- Inserción de motivos de baja
INSERT INTO motivos_baja (motivo, siglas, descripcion) VALUES
('BAJA DIA 1', 'B1', 'Deserción el primer día de capacitación'),
('NO CONTACTO', 'NC', 'No se pudo contactar al postulante'),
('FAMILIAR', 'FAM', 'Problemas de índole familiar'),
('SALUD', 'SAL', 'Problemas médicos / salud'),
('ECONÓMICO', 'ECO', 'Problemas económicos o de transporte'),
('DISTANCIA', 'DIS', 'La sede de trabajo o capacitación le queda muy lejos'),
('ESTUDIOS', 'EST', 'Cruce de horarios con estudios'),
('VIAJE', 'VIA', 'Viaje imprevisto o planificado'),
('OFERTA LABORAL', 'OFE', 'Aceptó otra oferta laboral')
ON CONFLICT (motivo) DO NOTHING;

-- 6. Tabla de Grupos de Capacitación
CREATE TABLE IF NOT EXISTS grupos_capacitacion (
    codigo VARCHAR(50) PRIMARY KEY, -- Ej: 'GPE-2026027'
    campana_id BIGINT REFERENCES campanas(id) ON DELETE RESTRICT,
    formador_documento VARCHAR(20) REFERENCES formadores(documento) ON DELETE RESTRICT,
    fecha_registro DATE NOT NULL,
    modalidad VARCHAR(50) DEFAULT 'PRESENCIAL' CONSTRAINT chk_modalidad CHECK (modalidad IN ('PRESENCIAL', 'REMOTO')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 7. Tabla de Postulantes (Nómina Principal)
CREATE TABLE IF NOT EXISTS postulantes (
    documento VARCHAR(30) PRIMARY KEY, -- DNI o C.E.
    tipo_documento VARCHAR(10) NOT NULL DEFAULT 'DNI' CONSTRAINT chk_tipo_doc CHECK (tipo_documento IN ('DNI', 'CE', 'PASAPORTE')),
    apellido_paterno VARCHAR(100) NOT NULL,
    apellido_materno VARCHAR(100) NOT NULL,
    nombres VARCHAR(150) NOT NULL,
    celular VARCHAR(30) CONSTRAINT chk_celular CHECK (celular ~ '^[0-9#\s\+\-]+$'), -- Solo números o caracteres telefónicos
    celular_referencia VARCHAR(30),
    correo VARCHAR(255) CONSTRAINT chk_correo CHECK (correo ~* '^[A-Za-z0-9._%-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}$'), -- Regex simple para email
    genero VARCHAR(20) CONSTRAINT chk_genero CHECK (genero IN ('MASCULINO', 'FEMENINO')),
    fecha_nacimiento DATE CONSTRAINT chk_fecha_nac CHECK (fecha_nacimiento < CURRENT_DATE - INTERVAL '15 years'), -- Edad mínima 15 años
    estado_civil VARCHAR(50) CONSTRAINT chk_estado_civil CHECK (estado_civil IN ('SOLTERO', 'CASADO', 'DIVORCIADO', 'CONVIVIENTE', 'VIUDO')),
    n_hijos INTEGER DEFAULT 0 CONSTRAINT chk_hijos CHECK (n_hijos >= 0),
    nivel_academico VARCHAR(100),
    periodo_reclutado VARCHAR(10), -- Ej: '202604'
    semana_trabajo INTEGER CONSTRAINT chk_semana CHECK (semana_trabajo BETWEEN 1 AND 53),
    reclutador_id BIGINT REFERENCES reclutadores(id) ON DELETE SET NULL,
    sede_id BIGINT REFERENCES sedes(id) ON DELETE RESTRICT,
    campana_id BIGINT REFERENCES campanas(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 8. Asistencias de Capacitación (Diarias o por Sesión)
CREATE TABLE IF NOT EXISTS asistencias_capacitacion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    postulante_documento VARCHAR(30) REFERENCES postulantes(documento) ON DELETE CASCADE,
    grupo_codigo VARCHAR(50) REFERENCES grupos_capacitacion(codigo) ON DELETE RESTRICT,
    fecha_asistencia DATE NOT NULL,
    sigla_asistencia VARCHAR(10) NOT NULL CONSTRAINT chk_sigla CHECK (sigla_asistencia IN ('A', 'I-OP', 'B', 'FI', 'FJ')), -- Asistencia, Ingreso Operación, Baja, Falta Injustificada, Falta Justificada
    motivo_baja VARCHAR(100) REFERENCES motivos_baja(motivo) ON DELETE RESTRICT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    
    -- Restricción para evitar registrar asistencia del mismo postulante en el mismo grupo en el mismo día
    CONSTRAINT uq_postulante_fecha_grupo UNIQUE (postulante_documento, grupo_codigo, fecha_asistencia),
    -- Validación de consistencia: si es Baja (B), debe tener motivo. Si no lo es, motivo debe ser NULL.
    CONSTRAINT chk_baja_con_motivo CHECK (
        (sigla_asistencia = 'B' AND motivo_baja IS NOT NULL) OR 
        (sigla_asistencia != 'B' AND motivo_baja IS NULL)
    )
);

-- 9. Evaluaciones de Capacitación
CREATE TABLE IF NOT EXISTS evaluaciones_capacitacion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    postulante_documento VARCHAR(30) REFERENCES postulantes(documento) ON DELETE CASCADE UNIQUE,
    grupo_codigo VARCHAR(50) REFERENCES grupos_capacitacion(codigo) ON DELETE RESTRICT,
    alfabetidad NUMERIC(3, 1) CONSTRAINT chk_alfabetidad CHECK (alfabetidad BETWEEN 0 AND 10),
    orientacion_cliente NUMERIC(3, 1) CONSTRAINT chk_orientacion CHECK (orientacion_cliente BETWEEN 0 AND 10),
    habilidades_contacto NUMERIC(3, 1) CONSTRAINT chk_habilidades CHECK (habilidades_contacto BETWEEN 0 AND 10),
    resultado VARCHAR(30) NOT NULL CONSTRAINT chk_resultado CHECK (resultado IN ('APROBADO', 'DESAPROBADO', 'NO DA EVALUAR')),
    observaciones TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 10. Bitácora de Auditoría (Audit Logs)
CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tabla_afectada VARCHAR(100) NOT NULL,
    operacion VARCHAR(10) NOT NULL, -- 'INSERT', 'UPDATE', 'DELETE'
    id_registro VARCHAR(100) NOT NULL,
    valores_anteriores JSONB,
    valores_nuevos JSONB,
    usuario_email VARCHAR(255),
    fecha TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 11. Función PL/pgSQL para disparador de Auditoría Automática
CREATE OR REPLACE FUNCTION procesar_auditoria()
RETURNS TRIGGER AS $$
DECLARE
    v_valores_anteriores JSONB := NULL;
    v_valores_nuevos JSONB := NULL;
    v_id_registro VARCHAR(100);
    v_usuario_email VARCHAR(255);
BEGIN
    -- Intentar obtener el correo de usuario de Supabase Auth metadata
    BEGIN
        v_usuario_email := COALESCE(
            current_setting('request.jwt.claim.email', true),
            'system'
        );
    EXCEPTION WHEN OTHERS THEN
        v_usuario_email := 'system';
    END;

    IF (TG_OP = 'DELETE') THEN
        v_valores_anteriores := to_jsonb(OLD);
        -- Obtener llave primaria como ID de registro
        IF TG_TABLE_NAME = 'postulantes' THEN
            v_id_registro := OLD.documento;
        ELSE
            v_id_registro := OLD.id::text;
        END IF;
    ELSIF (TG_OP = 'UPDATE') THEN
        v_valores_anteriores := to_jsonb(OLD);
        v_valores_nuevos := to_jsonb(NEW);
        IF TG_TABLE_NAME = 'postulantes' THEN
            v_id_registro := NEW.documento;
        ELSE
            v_id_registro := NEW.id::text;
        END IF;
    ELSIF (TG_OP = 'INSERT') THEN
        v_valores_nuevos := to_jsonb(NEW);
        IF TG_TABLE_NAME = 'postulantes' THEN
            v_id_registro := NEW.documento;
        ELSE
            v_id_registro := NEW.id::text;
        END IF;
    END IF;

    INSERT INTO audit_logs(tabla_afectada, operacion, id_registro, valores_anteriores, valores_nuevos, usuario_email)
    VALUES (TG_TABLE_NAME, TG_OP, v_id_registro, v_valores_anteriores, v_valores_nuevos, v_usuario_email);

    IF (TG_OP = 'DELETE') THEN
        RETURN OLD;
    ELSE
        RETURN NEW;
    END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 12. Creación de Disparadores (Triggers) de Auditoría
CREATE TRIGGER audit_postulantes_trigger
AFTER INSERT OR UPDATE OR DELETE ON postulantes
FOR EACH ROW EXECUTE FUNCTION procesar_auditoria();

CREATE TRIGGER audit_asistencias_trigger
AFTER INSERT OR UPDATE OR DELETE ON asistencias_capacitacion
FOR EACH ROW EXECUTE FUNCTION procesar_auditoria();

CREATE TRIGGER audit_evaluaciones_trigger
AFTER INSERT OR UPDATE OR DELETE ON evaluaciones_capacitacion
FOR EACH ROW EXECUTE FUNCTION procesar_auditoria();
