-- 1. Agregar columna de meta grupal a campanas
ALTER TABLE public.campanas ADD COLUMN IF NOT EXISTS meta_grupal INTEGER DEFAULT 0;

-- 2. Crear tabla relacional para conformar equipos y metas individuales
CREATE TABLE IF NOT EXISTS public.campana_reclutadores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campana_id BIGINT REFERENCES public.campanas(id) ON DELETE CASCADE,
    reclutador_id BIGINT REFERENCES public.reclutadores(id) ON DELETE CASCADE,
    meta_individual INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    CONSTRAINT uq_campana_reclutador UNIQUE (campana_id, reclutador_id)
);

-- 3. Habilitar RLS en la nueva tabla
ALTER TABLE public.campana_reclutadores ENABLE ROW LEVEL SECURITY;

-- 4. Crear políticas RLS para la nueva tabla y actualizar la de campañas
DROP POLICY IF EXISTS select_campana_reclutadores ON public.campana_reclutadores;
DROP POLICY IF EXISTS insert_campana_reclutadores ON public.campana_reclutadores;
DROP POLICY IF EXISTS update_campana_reclutadores ON public.campana_reclutadores;
DROP POLICY IF EXISTS delete_campana_reclutadores ON public.campana_reclutadores;

CREATE POLICY select_campana_reclutadores ON public.campana_reclutadores FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY insert_campana_reclutadores ON public.campana_reclutadores FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY update_campana_reclutadores ON public.campana_reclutadores FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY delete_campana_reclutadores ON public.campana_reclutadores FOR DELETE TO anon, authenticated USING (true);

DROP POLICY IF EXISTS update_campanas ON public.campanas;
CREATE POLICY update_campanas ON public.campanas FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
