-- Tablas para Registro y Calibración del Día 1

-- 1. Tabla de Configuración de Día 1 por Grupo
CREATE TABLE IF NOT EXISTS grupos_dia1 (
    grupo_codigo VARCHAR(50) PRIMARY KEY REFERENCES grupos_capacitacion(codigo) ON DELETE CASCADE,
    fecha_dia1 DATE NOT NULL,
    estado_calibracion VARCHAR(20) DEFAULT 'PENDIENTE' CONSTRAINT chk_estado_calib CHECK (estado_calibracion IN ('PENDIENTE', 'CALIBRADO', 'DESCALIBRADO')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Tabla de Asistencias del Reclutador (Día 1)
CREATE TABLE IF NOT EXISTS asistencias_dia1_reclutador (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    postulante_documento VARCHAR(30) REFERENCES postulantes(documento) ON DELETE CASCADE,
    grupo_codigo VARCHAR(50) REFERENCES grupos_capacitacion(codigo) ON DELETE RESTRICT,
    sigla_asistencia VARCHAR(10) NOT NULL CONSTRAINT chk_sigla_rec CHECK (sigla_asistencia IN ('A', 'I-OP', 'B', 'FI', 'FJ')),
    motivo_baja VARCHAR(100) REFERENCES motivos_baja(motivo) ON DELETE RESTRICT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    
    CONSTRAINT uq_postulante_grupo_dia1 UNIQUE (postulante_documento, grupo_codigo),
    CONSTRAINT chk_baja_con_motivo_dia1 CHECK (
        (sigla_asistencia = 'B' AND motivo_baja IS NOT NULL) OR 
        (sigla_asistencia != 'B' AND motivo_baja IS NULL)
    )
);

-- Habilitar RLS (Opcional, pero recomendado si usas anon key)
ALTER TABLE grupos_dia1 ENABLE ROW LEVEL SECURITY;
ALTER TABLE asistencias_dia1_reclutador ENABLE ROW LEVEL SECURITY;

-- Políticas de acceso público (ya que la app usa anon key para todo)
CREATE POLICY "Public Access grupos_dia1" ON grupos_dia1 FOR ALL USING (true);
CREATE POLICY "Public Access asistencias_dia1_reclutador" ON asistencias_dia1_reclutador FOR ALL USING (true);
