-- ==============================================================================
-- MIGRACIÓN MAESTRA: Sincronización y Gobernanza de Formadores y Supervisores
-- Base de Datos: GEA Dashboard (Supabase PostgreSQL)
-- Total Registros: 75 colaboradores clasificados por Segmento y Sede
-- ==============================================================================

-- 1. Inserción / Actualización en la tabla maestra 'formadores' (UPSERT por DNI)
INSERT INTO public.formadores (
  documento,
  nombre_completo,
  sede,
  segmento,
  subcampana,
  cargo_contractual,
  cargo_funcional,
  estado,
  fecha_inicio,
  fecha_cese
) VALUES
  -- ==========================================
  -- SEGMENTO: CLARO CHILE (Sede: ATE)
  -- ==========================================
  ('45322369', 'CINTHYA KATHERINE ARAUCO CHAVEZ', 'ATE', 'CLARO CHILE', 'POSTPAGO', 'FORMADOR', 'FORMADOR', 'Activo', '2023-05-06', NULL),
  ('76518936', 'MICHAEL BRYEN ELESCANO ANCHIRAICO', 'ATE', 'CLARO CHILE', 'POSTPAGO', 'FORMADOR', 'FORMADOR', 'Activo', '2025-01-01', NULL),
  ('46592535', 'PEDRO BRYAN FLORES LAZO', 'ATE', 'CLARO CHILE', 'POSTPAGO', 'SUPERVISOR DE CAPACITACION', 'SUPERVISOR', 'Activo', '2025-07-02', NULL),
  ('3982473',  'JOHANA DESIREE LUGO CALDERÓN', 'ATE', 'CLARO CHILE', 'POSTPAGO', 'FORMADOR', 'FORMADOR', 'Activo', '2025-09-01', NULL),
  ('4281528',  'CARLOS ALBERTO RUIZ CASTAÑEDA', 'ATE', 'CLARO CHILE', 'POSTPAGO', 'FORMADOR', 'FORMADOR', 'Activo', '2025-09-01', NULL),
  ('75668861', 'JHON MILLER CARBAJAL VARGAS', 'ATE', 'CLARO CHILE', 'POSTPAGO', 'FORMADOR', 'FORMADOR', 'Activo', '2025-09-01', NULL),
  ('73077184', 'FERNANDO NOE OYARCE RAMIREZ', 'ATE', 'CLARO CHILE', 'POSTPAGO', 'FORMADOR', 'FORMADOR', 'Activo', '2026-02-02', NULL),
  ('77046338', 'CHRISTIAN ANTONIO YGNACIO CARBAJAL', 'ATE', 'CLARO CHILE', 'POSTPAGO', 'FORMADOR', 'FORMADOR', 'Activo', '2026-04-06', NULL),
  ('47539064', 'JEFFERSON EDUARDO PEVES ROJAS', 'ATE', 'CLARO CHILE', 'POSTPAGO', 'FORMADOR', 'FORMADOR', 'Activo', '2026-06-02', NULL),
  ('74321134', 'CARLOS JOAQUÍN PINCHI MONTECILLO', 'ATE', 'CLARO CHILE', 'POSTPAGO', 'FORMADOR', 'FORMADOR', 'Activo', '2026-08-01', NULL),

  -- ==========================================
  -- SEGMENTO: CLARO PERU (Sede: JOCKEY PLAZA)
  -- ==========================================
  ('75161306', 'KAROL LIZETTE EUSEBIO CAMAVILCA', 'JOCKEY PLAZA', 'CLARO PERU', 'CLARO POSTPAGO - CROSS', 'FORMADOR', 'FORMADOR', 'Activo', '2024-08-26', NULL),
  ('42828450', 'LESLIE ALLISON RIVERA ROMERO', 'JOCKEY PLAZA', 'CLARO PERU', 'CLARO POSTPAGO', 'SUPERVISOR DE CAPACITACION', 'SUPERVISOR', 'Activo', '2025-07-14', NULL),
  ('46157239', 'DANIELA ESPERANZA BALLUMBROSIO FLORES DE MEZA', 'JOCKEY PLAZA', 'CLARO PERU', 'CLARO POSTPAGO', 'FORMADOR', 'FORMADOR', 'Activo', '2025-11-17', NULL),
  ('76714787', 'ASTRID SOPHIA EYZAGUIRRE DE FREITAS', 'JOCKEY PLAZA', 'CLARO PERU', 'CLARO POSTPAGO', 'FORMADOR', 'FORMADOR', 'Activo', '2025-11-17', NULL),
  ('45922295', 'MARCO ANTONIO DIAZ MURRIETA', 'JOCKEY PLAZA', 'CLARO PERU', 'CLARO POSTPAGO', 'FORMADOR', 'FORMADOR', 'Activo', '2025-12-01', NULL),
  ('42212560', 'CINTHYA ELIZABETH BEJARANO SOTO', 'JOCKEY PLAZA', 'CLARO PERU', 'CLARO POSTPAGO', 'COORDINADOR DE CAPACITACION', 'COORDINADOR', 'Activo', '2025-12-10', NULL),
  ('2528343',  'JESUS DANIEL NAVARRO RUIZ', 'JOCKEY PLAZA', 'CLARO PERU', 'CLARO POSTPAGO', 'SUPERVISOR DE CAPACITACION', 'SUPERVISOR', 'Activo', '2025-12-15', NULL),
  ('72196608', 'JOSE CARLOS MARIN FLORES', 'JOCKEY PLAZA', 'CLARO PERU', 'CLARO POSTPAGO', 'FORMADOR', 'FORMADOR', 'Activo', '2025-12-15', NULL),
  ('74738145', 'KAROL XIOMARA RUMINO PELAEZ', 'JOCKEY PLAZA', 'CLARO PERU', 'CLARO POSTPAGO', 'FORMADOR', 'FORMADOR', 'Activo', '2025-12-15', NULL),
  ('75948069', 'DANILO ALDAIR VELASQUEZ TESEN', 'JOCKEY PLAZA', 'CLARO PERU', 'CLARO POSTPAGO', 'FORMADOR', 'FORMADOR', 'Activo', '2025-12-17', NULL),
  ('46717733', 'FLAVIO HERNAN GUTIERREZ CANO', 'JOCKEY PLAZA', 'CLARO PERU', 'CLARO POSTPAGO', 'FORMADOR', 'FORMADOR', 'Activo', '2026-01-04', NULL),
  ('74610863', 'RENZO AARON FRANCIA WIDDUP', 'JOCKEY PLAZA', 'CLARO PERU', 'CLARO POSTPAGO', 'FORMADOR', 'FORMADOR', 'Activo', '2026-03-05', NULL),
  ('47617817', 'MARCO ANTONIO ALVARADO AVILA', 'JOCKEY PLAZA', 'CLARO PERU', 'CLARO POSTPAGO', 'FORMADOR', 'FORMADOR', 'Activo', '2026-03-17', NULL),
  ('45648683', 'JOSÉ MARTÍN SALAZAR MUÑOZ', 'JOCKEY PLAZA', 'CLARO PERU', 'CLARO POSTPAGO', 'FORMADOR', 'FORMADOR', 'Activo', '2026-03-23', NULL),
  ('46709568', 'DAYSI FABIOLA GARCIA PRADO', 'JOCKEY PLAZA', 'CLARO PERU', 'CLARO POSTPAGO', 'FORMADOR', 'FORMADOR', 'Activo', '2026-03-23', NULL),
  ('46712500', 'PAOLA ANTHUANET CARRILLO LOPEZ', 'JOCKEY PLAZA', 'CLARO PERU', 'CLARO POSTPAGO', 'PASANTIA', 'FORMADOR', 'Activo', '2026-05-01', NULL),
  ('71882653', 'ANTONIO FRANCESCO GUTIERREZ RIGETTI', 'JOCKEY PLAZA', 'CLARO PERU', 'CLARO POSTPAGO', 'FORMADOR', 'FORMADOR', 'Activo', '2026-05-04', NULL),
  ('76996405', 'JUAQUIN MATEO PALOMINO BEZADA', 'JOCKEY PLAZA', 'CLARO PERU', 'CLARO RETENCIONES FIJA', 'FORMADOR', 'FORMADOR', 'Activo', '2026-05-04', NULL),
  ('2157988',  'YOMALIS SARAIS LOPEZ GUZMAN', 'JOCKEY PLAZA', 'CLARO PERU', 'CLARO POSTPAGO', 'FORMADOR', 'FORMADOR', 'Activo', '2026-06-03', NULL),
  ('71653289', 'EDWARD ANDRES MONGE SOCOLA', 'JOCKEY PLAZA', 'CLARO PERU', 'RETENCIONES FIJA INBOUND', 'FORMADOR', 'FORMADOR', 'Activo', '2026-06-09', NULL),
  ('10235900', 'ANA CORINA AGUIRRE HUAYAMARES', 'JOCKEY PLAZA', 'CLARO PERU', 'CLARO POSTPAGO - CROSS', 'FORMADOR', 'FORMADOR', 'Activo', '2026-06-23', NULL),
  ('43614771', 'SANDRA CAVERO MONTES', 'JOCKEY PLAZA', 'CLARO PERU', 'CLARO POSTPAGO', 'SUPERVISOR DE CAPACITACION', 'SUPERVISOR', 'Activo', '2026-06-22', NULL),

  -- ==========================================
  -- SEGMENTO: CLARO PERU OUT (Sedes: JOCKEY PLAZA / ATE)
  -- ==========================================
  ('70854319', 'MARTIN CAMPOSANO JULI', 'JOCKEY PLAZA', 'CLARO PERU OUT', 'OLAS', 'FORMADOR', 'FORMADOR', 'Activo', '2025-01-01', NULL),
  ('73019892', 'GERALDINE MILAGROS TACURI HUERTAS', 'JOCKEY PLAZA', 'CLARO PERU OUT', 'MIGRACIONES ESPECIALES - OUT', 'FORMADOR', 'FORMADOR', 'Activo', '2025-01-01', NULL),
  ('73769262', 'GIOVANNY VALDEMAR GUTIERREZ CHARUN', 'JOCKEY PLAZA', 'CLARO PERU OUT', 'RENOVACIONES ESPECIALES - OUT', 'FORMADOR', 'FORMADOR', 'Activo', '2025-01-01', NULL),
  ('73890253', 'LADY NICOLE CARBAJAL VERASTEGUI', 'JOCKEY PLAZA', 'CLARO PERU OUT', 'RENOVACIONES ESPECIALES - WSP', 'FORMADOR', 'FORMADOR', 'Activo', '2025-01-01', NULL),
  ('74536191', 'JACKSON ESPINOZA GAMARRA', 'ATE', 'CLARO PERU OUT', 'RENOVACIONES ESPECIALES - WSP', 'JEFE DE CAPACITACION', 'JEFATURA', 'Activo', '2025-01-01', NULL),
  ('43306342', 'ROBERTO LUIS SERNAQUE NEIRA', 'ATE', 'CLARO PERU OUT', 'RENOVACIONES ESPECIALES - OUT', 'SUPERVISOR DE CAPACITACION', 'SUPERVISOR', 'Activo', '2026-01-01', NULL),
  ('70848935', 'ROBERTO ANGEL MORALES VASQUEZ', 'ATE', 'CLARO PERU OUT', 'MIGRACIONES ESPECIALES - OUT', 'FORMADOR', 'FORMADOR', 'Activo', '2026-02-18', NULL),
  ('73475051', 'ARACELI YARO PEREZ', 'JOCKEY PLAZA', 'CLARO PERU OUT', 'RENOVACIONES ESPECIALES - OUT', 'FORMADOR', 'FORMADOR', 'Activo', '2026-03-12', NULL),
  ('6481237',  'RITZARY DEL CARMENN DE FREITES GONZALEZ', 'ATE', 'CLARO PERU OUT', 'OLAS', 'PASANTIA', 'FORMADOR', 'Activo', '2026-03-14', NULL),
  ('78458522', 'XIOMARA MARELLY HUARCAYA CARRILLO', 'ATE', 'CLARO PERU OUT', 'UPGRADE', 'FORMADOR', 'FORMADOR', 'Activo', '2026-05-25', NULL),
  ('6816764',  'ENRIQUE CHÁVEZ CALERO', 'ATE', 'CLARO PERU OUT', 'UPGRADE', 'FORMADOR', 'FORMADOR', 'Activo', '2026-07-08', NULL),

  -- ==========================================
  -- SEGMENTO: CLARO PERU RETENCIONES (Sedes: COMAS / SAN ISIDRO)
  -- ==========================================
  ('45322864', 'CINTHIA PAOLA DEL MILAGRO RUIZ CHICOMA DE CHUMAN', 'COMAS', 'CLARO PERU RETENCIONES', 'CONTACTADOS', 'FORMADOR', 'FORMADOR', 'Activo', '2025-01-01', NULL),
  ('45531674', 'JHOJAN CHRISTIAN SALVADOR DE PAZ', 'COMAS', 'CLARO PERU RETENCIONES', 'CONTACTADOS', 'PASANTIA', 'SUPERVISOR', 'Activo', '2025-01-01', NULL),
  ('74174478', 'HECTOR ADRIAN PACHERRE TORRES', 'SAN ISIDRO', 'CLARO PERU RETENCIONES', 'RETENCIONES INBOUND', 'FORMADOR', 'FORMADOR', 'Activo', '2025-01-01', NULL),
  ('75574487', 'JACKELINE KARINA DUENAS DE LA CRUZ', 'SAN ISIDRO', 'CLARO PERU RETENCIONES', 'MI CLARO', 'FORMADOR', 'FORMADOR', 'Activo', '2025-01-01', NULL),
  ('75956763', 'MAYHOLI SELENE GUEVARA AGAPITO', 'SAN ISIDRO', 'CLARO PERU RETENCIONES', 'RETENCIONES INBOUND', 'FORMADOR', 'TEAM LEADER', 'Activo', '2025-01-01', NULL),
  ('74952090', 'VALERIA JAZMIN MARTEL CABRERA', 'COMAS', 'CLARO PERU RETENCIONES', 'CONTACTADOS', 'PASANTIA', 'FORMADOR', 'Activo', '2025-06-26', NULL),
  ('46253668', 'OSCAR ALFREDO URQUIAGA CANO', 'COMAS', 'CLARO PERU RETENCIONES', 'CONTACTADOS', 'PASANTIA', 'FORMADOR', 'Activo', '2025-09-01', NULL),
  ('77684232', 'RAFAEL DE LA CRUZ VENTURA', 'COMAS', 'CLARO PERU RETENCIONES', 'CONTACTADOS', 'FORMADOR', 'FORMADOR', 'Activo', '2025-10-07', NULL),
  ('75326078', 'GRYSLY LUCERO CARCAMO CHIROQUE', 'COMAS', 'CLARO PERU RETENCIONES', 'CONSULTA PREVIA', 'PASANTIA', 'FORMADOR', 'Activo', '2025-11-17', NULL),
  ('73446765', 'DANNA MITSUKO ANJELI SALAZAR FERRO', 'COMAS', 'CLARO PERU RETENCIONES', 'CONTACTADOS', 'PASANTIA', 'FORMADOR', 'Activo', '2026-01-08', NULL),
  ('4303055',  'CARLOS ANDRES MONTES ROMERO', 'COMAS', 'CLARO PERU RETENCIONES', 'CONTACTADOS', 'PASANTIA', 'FORMADOR', 'Activo', '2026-02-06', NULL),
  ('46686519', 'AGUSTIN PEREZ CASAFRANCA', 'SAN ISIDRO', 'CLARO PERU RETENCIONES', 'RETENCIONES INBOUND', 'FORMADOR', 'FORMADOR', 'Activo', '2026-03-01', NULL),
  ('77086527', 'SARA GABRIELA BALVIN GALINDO', 'SAN ISIDRO', 'CLARO PERU RETENCIONES', 'RETENCIONES INBOUND', 'FORMADOR', 'FORMADOR', 'Activo', '2026-04-01', NULL),
  ('46166217', 'JUAN JOSÉ DIAZ CABANILLAS', 'SAN ISIDRO', 'CLARO PERU RETENCIONES', 'RETENCIONES INBOUND', 'SUPERVISOR DE CAPACITACION', 'SUPERVISOR', 'Activo', '2026-05-04', NULL),
  ('72721826', 'ENRIQUE FERNANDO DE JESÚS SALGADO TORRES', 'SAN ISIDRO', 'CLARO PERU RETENCIONES', 'RETENCIONES INBOUND', 'FORMADOR', 'FORMADOR', 'Activo', '2026-05-04', NULL),
  ('74582278', 'ARIANA LIZBETH URBIZAGASTEGUI CANALES', 'SAN ISIDRO', 'CLARO PERU RETENCIONES', 'CANAL DIGITAL WSP INBOUND', 'ASESOR', 'APOYO FORMACION', 'Activo', '2026-05-05', NULL),
  ('45800905', 'LUIS CARLO RIVAS ZEVALLOS', 'SAN ISIDRO', 'CLARO PERU RETENCIONES', 'RETENCIONES INBOUND', 'SUPERVISOR DE CAPACITACION', 'SUPERVISOR', 'Activo', '2026-05-16', NULL),
  ('73991637', 'MERCEDES LISBETH CHUNGA ECHE', 'SAN ISIDRO', 'CLARO PERU RETENCIONES', 'RETENCIONES INBOUND', 'FORMADOR', 'FORMADOR', 'Activo', '2026-06-13', NULL),
  ('73044762', 'CINTHIA SOFIA MORI POLICARPIO', 'COMAS', 'CLARO PERU RETENCIONES', 'CONTACTADOS', 'FORMADOR', 'FORMADOR', 'Activo', '2026-08-01', NULL),
  ('75357042', 'ROSA ANGELINA DURAND AGUILAR', 'SAN ISIDRO', 'CLARO PERU RETENCIONES', 'RETENCIONES INBOUND', 'FORMADOR', 'FORMADOR', 'Activo', '2026-08-03', NULL),
  ('70436112', 'PEDRO GABRIEL DIAZ MURRIETA', 'SAN ISIDRO', 'CLARO PERU RETENCIONES', 'RETENCIONES INBOUND', 'FORMADOR', 'FORMADOR', 'Activo', '2026-07-27', NULL),
  ('44509308', 'ALI BAUMANN LLERENA', 'SAN ISIDRO', 'CLARO PERU RETENCIONES', 'RETENCIONES INBOUND', 'FORMADOR', 'FORMADOR', 'Activo', '2026-08-04', NULL),
  ('76881658', 'MARIA ALEJANDRA GARCIA CARRERA', 'SAN ISIDRO', 'CLARO PERU RETENCIONES', 'RETENCIONES INBOUND', 'PASANTIA', 'FORMADOR', 'Activo', '2026-08-03', NULL),
  ('77569050', 'CRISTHIAN ALEXANDER ALVARADO CUADROS', 'COMAS', 'CLARO PERU RETENCIONES', 'CONTACTADOS', 'PASANTIA', 'FORMADOR', 'Activo', '2026-07-01', NULL),

  -- ==========================================
  -- SEGMENTO: LIPIGAS (Sede: ATE)
  -- ==========================================
  ('73436227', 'WINNIE DEXTRE SANCHEZ', 'ATE', 'LIPIGAS', 'LIMA GAS', 'FORMADOR', 'FORMADOR', 'Activo', '2023-06-01', NULL),
  ('76697386', 'BRIGUITH BOCANEGRA CEOPA', 'ATE', 'LIPIGAS', 'TUVES', 'FORMADOR', 'FORMADOR', 'Activo', '2025-01-01', NULL),
  ('957294',   'DANY FERNANDO PASACHOA PRASCA', 'ATE', 'LIPIGAS', 'LIPIGAS SAC', 'JEFE DE CAPACITACION', 'JEFATURA', 'Activo', '2025-04-22', NULL),
  ('10375652', 'CARMEN LILIANA LUNA DÍAZ', 'ATE', 'LIPIGAS', 'LIPIGAS TPE', 'FORMADOR', 'FORMADOR', 'Activo', '2025-04-22', NULL),
  ('41714955', 'WALTER JUNIOR SERNAQUE REPETTO', 'ATE', 'LIPIGAS', 'LIPIGAS TPE', 'SUPERVISOR DE CAPACITACION', 'SUPERVISOR', 'Activo', '2026-01-01', NULL),
  ('61361597', 'AARON ABRAHAM NELSON AMAYA MACALUPU', 'ATE', 'LIPIGAS', 'TUVES BOLIVIA', 'FORMADOR', 'FORMADOR', 'Activo', '2026-02-09', NULL),
  ('43512161', 'MARIA LUISA BANCAYAN PANANA DE VEGA', 'ATE', 'LIPIGAS', 'LIPIGAS TPE', 'FORMADOR', 'FORMADOR', 'Activo', '2026-05-27', NULL),
  ('46567625', 'ALBERTO AGUSTIN GALVEZ CERECEDA', 'ATE', 'LIPIGAS', 'LIPIGAS TPE', 'APOYO', 'FORMADOR', 'Activo', '2026-06-10', NULL)

ON CONFLICT (documento) DO UPDATE SET
  nombre_completo   = EXCLUDED.nombre_completo,
  sede              = EXCLUDED.sede,
  segmento          = EXCLUDED.segmento,
  subcampana        = EXCLUDED.subcampana,
  cargo_contractual = EXCLUDED.cargo_contractual,
  cargo_funcional   = EXCLUDED.cargo_funcional,
  estado            = EXCLUDED.estado,
  fecha_inicio      = EXCLUDED.fecha_inicio;

-- ==============================================================================
-- 2. GOBERNANZA: Vinculación Automática de Segmentos a Perfiles de Supervisión
-- ==============================================================================

-- Claro Chile
UPDATE public.perfiles
SET segmento = 'CLARO CHILE'
WHERE nombre ILIKE '%FLORES LAZO PEDRO BRYAN%' OR nombre ILIKE '%PEDRO BRYAN FLORES LAZO%';

-- Claro Perú
UPDATE public.perfiles
SET segmento = 'CLARO PERU'
WHERE nombre ILIKE '%RIVERA ROMERO LESLIE ALLISON%' OR nombre ILIKE '%LESLIE ALLISON RIVERA ROMERO%'
   OR nombre ILIKE '%NAVARRO RUIZ JESUS DANIEL%' OR nombre ILIKE '%JESUS DANIEL NAVARRO RUIZ%'
   OR nombre ILIKE '%CAVERO MONTES SANDRA%' OR nombre ILIKE '%SANDRA CAVERO MONTES%';

-- Claro Perú OUT
UPDATE public.perfiles
SET segmento = 'CLARO PERU OUT'
WHERE nombre ILIKE '%SERNAQUE NEIRA ROBERTO LUIS%' OR nombre ILIKE '%ROBERTO LUIS SERNAQUE NEIRA%'
   OR nombre ILIKE '%ESPINOZA GAMARRA JACKSON%' OR nombre ILIKE '%JACKSON ESPINOZA GAMARRA%';

-- Claro Perú Retenciones
UPDATE public.perfiles
SET segmento = 'CLARO PERU RETENCIONES'
WHERE nombre ILIKE '%SALVADOR DE PAZ JHOJAN CHRISTIAN%' OR nombre ILIKE '%JHOJAN CHRISTIAN SALVADOR DE PAZ%'
   OR nombre ILIKE '%DIAZ CABANILLAS JUAN JOSÉ%' OR nombre ILIKE '%JUAN JOSÉ DIAZ CABANILLAS%'
   OR nombre ILIKE '%RIVAS ZEVALLOS LUIS CARLO%' OR nombre ILIKE '%LUIS CARLO RIVAS ZEVALLOS%';

-- Lipigas
UPDATE public.perfiles
SET segmento = 'LIPIGAS'
WHERE nombre ILIKE '%SERNAQUE REPETTO WALTER JUNIOR%' OR nombre ILIKE '%WALTER JUNIOR SERNAQUE REPETTO%'
   OR nombre ILIKE '%PASACHOA PRASCA DANY FERNANDO%' OR nombre ILIKE '%DANY FERNANDO PASACHOA PRASCA%';
