CREATE TABLE IF NOT EXISTS grupo_reclutadores (
  id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  grupo_codigo            VARCHAR(50) NOT NULL REFERENCES grupos_capacitacion(codigo) ON DELETE CASCADE,
  reclutador_id           BIGINT NOT NULL REFERENCES reclutadores(id) ON DELETE CASCADE,
  meta_rq_individual      INTEGER DEFAULT 0,
  meta_dia_1_individual   INTEGER DEFAULT 0,
  created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (grupo_codigo, reclutador_id)
);

-- Policies
ALTER TABLE grupo_reclutadores ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Todos pueden ver metas de grupo" ON grupo_reclutadores;
CREATE POLICY "Todos pueden ver metas de grupo"
  ON grupo_reclutadores FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "Solo autorizados pueden editar metas" ON grupo_reclutadores;
CREATE POLICY "Solo autorizados pueden editar metas"
  ON grupo_reclutadores FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM perfiles WHERE id = auth.uid() AND rol IN ('admin','formador','reclutador')))
  WITH CHECK (EXISTS (SELECT 1 FROM perfiles WHERE id = auth.uid() AND rol IN ('admin','formador','reclutador')));
