-- ==============================================================================
-- MIGRACIÓN: REVISIÓN DE ESTADO (DOCUMENTOS) Y BONO NOCTURNO (NÓMINAS)
-- Proyecto: GEA Dashboard / Portal WFM (ujqehcpglfhnytzsyedp)
-- Fecha: 2026-09-04
-- ==============================================================================

-- 1. Agregar columnas a la tabla nominas si no existen
ALTER TABLE public.nominas 
  ADD COLUMN IF NOT EXISTS revision_estado TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS bono_nocturno NUMERIC DEFAULT NULL;

-- 2. Actualizar la vista v_nominas_consolidado con las nuevas columnas
CREATE OR REPLACE VIEW public.v_nominas_consolidado AS
 SELECT n.documento AS nomina_id,
    n.documento,
    n.tipo_documento,
    n.apellido_paterno,
    n.apellido_materno,
    n.nombres,
    n.celular,
    n.celular_referencia,
    n.celular_emergencia,
    n.contacto_emergencia,
    n.parentesco,
    n.correo,
    n.genero,
    n.fecha_nacimiento,
    n.edad,
    n.estado_civil,
    n.n_hijos,
    n.nivel_academico,
    n.carrera,
    n.entidad,
    n.nacionalidad,
    n.lugar_nacimiento,
    n.lugar_residencia,
    n.distrito_residencia,
    n.direccion_domicilio,
    n.periodo_reclutado,
    n.semana_trabajo,
    n.reclutador,
    n.sede,
    n.campana,
    n.segmento,
    n.reclutador_id,
    n.fuente_oferta,
    n.observacion_reclutamiento,
    n.exp_call_center,
    n.exp_tipo_campana,
    COALESCE(n.exp_tiempo_campana, n.exp_tiempo_call::character varying) AS exp_tiempo_campana,
    n.exp_otra,
    n.exp_tiempo_otra,
    n.grupo_codigo,
    n.grupo_codigo AS grupo_codigo_alt,
    COALESCE(n.modalidad, cr.modalidad) AS modalidad,
    COALESCE(n.condicion, cr.condicion::text) AS condicion,
    COALESCE(n.horario_gestion, cr.rango_horario::text) AS horario_gestion,
    n.descanso,
    n.envio_dni,
    n.test_psicologico,
    n.validacion_pc,
    n.evaluacion_dia_0,
    n.fecha_inicio_capacitacion,
    n.fecha_fin_capacitacion,
    n.fecha_conexion_ojt,
    n.fecha_conexion_op,
    n.pago_capacitacion,
    n.fecha_inscripcion_curso,
    n.fecha_ingreso,
    n.tipo_trabajo,
    n.tipo_contratacion,
    n.razon_social,
    n.rango_salarial,
    n.remuneracion,
    n.bono_variable,
    n.bono_movilidad,
    n.bono_bienvenida,
    n.bono_permanencia,
    n.bono_asistencia_perfecta,
    n.cargo_contractual,
    n.dia_0,
    n.dia_0_obs,
    n.status_dia_1,
    n.dia_1,
    n.dia_1_obs,
    COALESCE(n.estado, n.status_final::character varying) AS estado,
    n.activo,
    n.doc_cv,
    n.doc_dni_adjunto,
    n.doc_certijoven,
    n.doc_recibo_servicios,
    n.doc_ficha_datos,
    n.doc_autorizacion,
    cr.area_traslado,
    cr.semana_label AS grupo_semana_label,
    cr.estado AS grupo_estado,
    cr.rango_horario AS grupo_rango_horario,
    cr.periodo AS grupo_periodo,
    cr.extension_teoria,
    cr.fecha_inicio_ojt AS grupo_fecha_inicio_ojt,
    cr.extension_ojt,
    cr.fecha_ingreso_op AS grupo_fecha_ingreso_op,
    cr.rq_solicitado,
    cr.rq_ftes_solicitado,
    cr.meta_dia_0,
    cr.meta_dia_1,
    n.created_at,
    n.marca_temporal,
    n.usuario_whatsapp,
    n.revision_estado,
    n.bono_nocturno
   FROM nominas n
     LEFT JOIN capacidad_rys cr ON n.grupo_codigo = cr.codigo::text AND n.campana = cr.campana::text
  WHERE n.activo = true;
