-- ============================================================
-- GEA DataCenter — Schema v2
-- Arquitectura escalable: Persona + Proceso de Nómina
-- Ejecutar en Supabase SQL Editor o via apply-schema-v2.js
-- ============================================================

-- ── ENUMS ───────────────────────────────────────────────────
DO $$ BEGIN CREATE TYPE app_role AS ENUM ('admin','reclutador','formador','visor');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN CREATE TYPE nomina_estado AS ENUM (
  'RECLUTADO','EN_CAPACITACION','EN_OJT','EN_OPERACION','BAJA','CESADO'
);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN CREATE TYPE modalidad_tipo AS ENUM ('PRESENCIAL','REMOTO','HIBRIDO');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ── CATÁLOGOS (dimensiones) ─────────────────────────────────
CREATE TABLE IF NOT EXISTS sedes (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre     VARCHAR(100) NOT NULL UNIQUE,
  activa     BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS campanas (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre     VARCHAR(150) NOT NULL UNIQUE,
  segmento   VARCHAR(100),
  supervisor VARCHAR(150),
  meta_grupal INTEGER DEFAULT 0,
  activa     BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS reclutadores (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_completo VARCHAR(200) NOT NULL UNIQUE,
  activo          BOOLEAN NOT NULL DEFAULT TRUE,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS campana_reclutadores (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campana_id      BIGINT NOT NULL REFERENCES campanas(id) ON DELETE CASCADE,
  reclutador_id   BIGINT NOT NULL REFERENCES reclutadores(id) ON DELETE CASCADE,
  meta_individual INTEGER DEFAULT 0,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (campana_id, reclutador_id)
);

CREATE TABLE IF NOT EXISTS formadores (
  documento         VARCHAR(20) PRIMARY KEY,
  nombre_completo   VARCHAR(200) NOT NULL,
  sede_id           BIGINT REFERENCES sedes(id) ON DELETE SET NULL,
  campana_id        BIGINT REFERENCES campanas(id) ON DELETE SET NULL,
  cargo_contractual VARCHAR(150),
  cargo_funcional   VARCHAR(150),
  estado            VARCHAR(50) NOT NULL DEFAULT 'Activo'
    CHECK (estado IN ('Activo','Cese')),
  fecha_inicio      DATE,
  fecha_cese        DATE,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS motivos_baja (
  motivo      VARCHAR(100) PRIMARY KEY,
  siglas      VARCHAR(20),
  descripcion TEXT
);

INSERT INTO motivos_baja (motivo, siglas, descripcion) VALUES
  ('BAJA DIA 1', 'B1', 'Deserción el primer día'),
  ('NO CONTACTO', 'NC', 'No se pudo contactar'),
  ('FAMILIAR', 'FAM', 'Problemas familiares'),
  ('SALUD', 'SAL', 'Problemas de salud'),
  ('ECONÓMICO', 'ECO', 'Problemas económicos'),
  ('DISTANCIA', 'DIS', 'Distancia a sede'),
  ('ESTUDIOS', 'EST', 'Cruce con estudios'),
  ('VIAJE', 'VIA', 'Viaje'),
  ('OFERTA LABORAL', 'OFE', 'Otra oferta laboral'),
  ('DICCION', 'DIC', 'Dicción'),
  ('RETIRO APROBADO POR JEFATURA', 'RET', 'Retiro aprobado')
ON CONFLICT (motivo) DO NOTHING;

CREATE TABLE IF NOT EXISTS grupos_capacitacion (
  codigo              VARCHAR(50) PRIMARY KEY,
  campana_id          BIGINT NOT NULL REFERENCES campanas(id) ON DELETE RESTRICT,
  formador_documento  VARCHAR(20) REFERENCES formadores(documento) ON DELETE SET NULL,
  fecha_registro      DATE NOT NULL,
  semana_trabajo      INTEGER CHECK (semana_trabajo BETWEEN 1 AND 53),
  modalidad           modalidad_tipo NOT NULL DEFAULT 'PRESENCIAL',
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ── PERSONA ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS postulantes (
  documento           VARCHAR(30) PRIMARY KEY,
  tipo_documento      VARCHAR(10) NOT NULL DEFAULT 'DNI'
    CHECK (tipo_documento IN ('DNI','CE','PASAPORTE')),
  apellido_paterno     VARCHAR(100) NOT NULL,
  apellido_materno     VARCHAR(100) NOT NULL,
  nombres              VARCHAR(150) NOT NULL,
  celular              VARCHAR(30),
  celular_referencia   VARCHAR(30),
  correo               VARCHAR(255),
  genero               VARCHAR(20) CHECK (genero IN ('MASCULINO','FEMENINO')),
  fecha_nacimiento     DATE,
  estado_civil         VARCHAR(50)
    CHECK (estado_civil IN ('SOLTERO','CASADO','DIVORCIADO','CONVIVIENTE','VIUDO')),
  n_hijos              INTEGER NOT NULL DEFAULT 0 CHECK (n_hijos >= 0),
  nivel_academico      VARCHAR(100),
  carrera              VARCHAR(150),
  nacionalidad         VARCHAR(80) DEFAULT 'PERUANA',
  lugar_residencia     VARCHAR(150),
  distrito_residencia  VARCHAR(100),
  direccion_domicilio  TEXT,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ── PROCESO DE NÓMINA (consolidado Excel) ───────────────────
CREATE TABLE IF NOT EXISTS nominas (
  id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  postulante_documento    VARCHAR(30) NOT NULL REFERENCES postulantes(documento) ON DELETE CASCADE,

  -- Reclutamiento
  periodo_reclutado       VARCHAR(10),
  semana_trabajo          INTEGER CHECK (semana_trabajo BETWEEN 1 AND 53),
  reclutador_id           BIGINT REFERENCES reclutadores(id) ON DELETE SET NULL,
  sede_id                 BIGINT REFERENCES sedes(id) ON DELETE SET NULL,
  campana_id              BIGINT REFERENCES campanas(id) ON DELETE SET NULL,
  fuente_oferta           VARCHAR(200),
  observacion_reclutamiento TEXT,

  -- Experiencia laboral
  exp_call_center         BOOLEAN,
  exp_tipo_campana        TEXT,
  exp_tiempo_campana      VARCHAR(80),
  exp_otra                TEXT,
  exp_tiempo_otra         VARCHAR(80),

  -- Capacitación / pipeline
  grupo_codigo            VARCHAR(50) REFERENCES grupos_capacitacion(codigo) ON DELETE SET NULL,
  modalidad               modalidad_tipo,
  condicion               VARCHAR(100),
  horario_gestion         VARCHAR(100),
  descanso                VARCHAR(100),
  envio_dni               DATE,
  test_psicologico        VARCHAR(50),
  validacion_pc           VARCHAR(50),
  evaluacion_dia_0        VARCHAR(50),
  fecha_inicio_capacitacion DATE,
  fecha_fin_capacitacion  DATE,
  fecha_conexion_ojt      DATE,
  fecha_conexion_op       DATE,
  pago_capacitacion       BOOLEAN DEFAULT FALSE,

  -- Contrato y compensación
  tipo_contratacion       VARCHAR(80),
  razon_social            VARCHAR(150),
  remuneracion            NUMERIC(10,2),
  bono_variable           NUMERIC(10,2),
  bono_movilidad          NUMERIC(10,2),
  bono_bienvenida         NUMERIC(10,2),
  bono_permanencia        NUMERIC(10,2),
  bono_asistencia_perfecta NUMERIC(10,2),
  cargo_contractual       VARCHAR(150),

  -- Seguimiento día 0 / día 1
  dia_0                   DATE,
  dia_0_obs               TEXT,
  status_dia_1            VARCHAR(80),
  dia_1                   DATE,
  dia_1_obs               TEXT,

  -- Estado del proceso
  estado                  nomina_estado NOT NULL DEFAULT 'RECLUTADO',
  activo                  BOOLEAN NOT NULL DEFAULT TRUE,

  created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_nominas_postulante ON nominas(postulante_documento);
CREATE INDEX IF NOT EXISTS idx_nominas_periodo ON nominas(periodo_reclutado);
CREATE INDEX IF NOT EXISTS idx_nominas_campana ON nominas(campana_id);
CREATE INDEX IF NOT EXISTS idx_nominas_estado ON nominas(estado);
CREATE INDEX IF NOT EXISTS idx_nominas_activo ON nominas(activo) WHERE activo = TRUE;

-- Solo un proceso activo por postulante
CREATE UNIQUE INDEX IF NOT EXISTS uq_nominas_postulante_activo
  ON nominas(postulante_documento) WHERE activo = TRUE;

-- ── ASISTENCIAS Y EVALUACIONES ──────────────────────────────
CREATE TABLE IF NOT EXISTS asistencias_capacitacion (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  postulante_documento VARCHAR(30) NOT NULL REFERENCES postulantes(documento) ON DELETE CASCADE,
  grupo_codigo         VARCHAR(50) NOT NULL REFERENCES grupos_capacitacion(codigo) ON DELETE RESTRICT,
  fecha_asistencia     DATE NOT NULL,
  sigla_asistencia     VARCHAR(10) NOT NULL
    CHECK (sigla_asistencia IN ('A','I-OP','B','FI','FJ')),
  motivo_baja          VARCHAR(100) REFERENCES motivos_baja(motivo) ON DELETE RESTRICT,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (postulante_documento, grupo_codigo, fecha_asistencia),
  CHECK (
    (sigla_asistencia = 'B' AND motivo_baja IS NOT NULL) OR
    (sigla_asistencia != 'B' AND motivo_baja IS NULL)
  )
);

CREATE TABLE IF NOT EXISTS evaluaciones_capacitacion (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  postulante_documento  VARCHAR(30) NOT NULL REFERENCES postulantes(documento) ON DELETE CASCADE,
  grupo_codigo          VARCHAR(50) NOT NULL REFERENCES grupos_capacitacion(codigo) ON DELETE RESTRICT,
  nomina_id             UUID REFERENCES nominas(id) ON DELETE SET NULL,
  alfabetidad           NUMERIC(3,1) CHECK (alfabetidad BETWEEN 0 AND 10),
  orientacion_cliente   NUMERIC(3,1) CHECK (orientacion_cliente BETWEEN 0 AND 10),
  habilidades_contacto  NUMERIC(3,1) CHECK (habilidades_contacto BETWEEN 0 AND 10),
  resultado             VARCHAR(30) NOT NULL
    CHECK (resultado IN ('APROBADO','DESAPROBADO','NO DA EVALUAR')),
  observaciones         TEXT,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (postulante_documento, grupo_codigo)
);

-- ── AUDITORÍA ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS audit_logs (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tabla_afectada     VARCHAR(100) NOT NULL,
  operacion          VARCHAR(10) NOT NULL,
  id_registro        VARCHAR(100) NOT NULL,
  valores_anteriores JSONB,
  valores_nuevos     JSONB,
  usuario_email      VARCHAR(255),
  fecha              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ── PERFILES (auth) ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS perfiles (
  id         UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  nombre     VARCHAR(200) NOT NULL,
  rol        app_role NOT NULL DEFAULT 'visor',
  cargo      VARCHAR(150),
  telefono   VARCHAR(30),
  avatar_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ── VISTA CONSOLIDADA (Excel operativo) ─────────────────────
CREATE OR REPLACE VIEW v_nominas_consolidado AS
SELECT
  n.id                          AS nomina_id,
  p.documento,
  p.tipo_documento,
  p.apellido_paterno,
  p.apellido_materno,
  p.nombres,
  p.celular,
  p.celular_referencia,
  p.correo,
  p.genero,
  p.fecha_nacimiento,
  EXTRACT(YEAR FROM AGE(CURRENT_DATE, p.fecha_nacimiento))::INTEGER AS edad,
  p.estado_civil,
  p.n_hijos,
  p.nivel_academico,
  p.carrera,
  p.nacionalidad,
  p.lugar_residencia,
  p.distrito_residencia,
  p.direccion_domicilio,
  n.periodo_reclutado,
  n.semana_trabajo,
  r.nombre_completo             AS reclutador,
  s.nombre                      AS sede,
  c.nombre                      AS campana,
  n.reclutador_id,
  n.sede_id,
  n.campana_id,
  n.fuente_oferta,
  n.observacion_reclutamiento,
  n.exp_call_center,
  n.exp_tipo_campana,
  n.exp_tiempo_campana,
  n.exp_otra,
  n.exp_tiempo_otra,
  n.grupo_codigo,
  n.modalidad::TEXT             AS modalidad,
  n.condicion,
  n.horario_gestion,
  n.descanso,
  n.envio_dni,
  n.test_psicologico,
  n.validacion_pc,
  n.evaluacion_dia_0,
  n.fecha_inicio_capacitacion,
  n.fecha_fin_capacitacion,
  n.fecha_conexion_ojt,
  n.fecha_conexion_op,
  n.pago_capacitacion,
  n.tipo_contratacion,
  n.razon_social,
  n.remuneracion,
  n.bono_variable,
  n.bono_movilidad,
  n.bono_bienvenida,
  n.bono_permanencia,
  n.bono_asistencia_perfecta,
  n.cargo_contractual,
  n.dia_0,
  n.dia_0_obs,
  n.status_dia_1,
  n.dia_1,
  n.dia_1_obs,
  n.estado::TEXT                AS estado,
  n.activo,
  p.created_at,
  n.updated_at
FROM nominas n
JOIN postulantes p ON p.documento = n.postulante_documento
LEFT JOIN reclutadores r ON r.id = n.reclutador_id
LEFT JOIN sedes s ON s.id = n.sede_id
LEFT JOIN campanas c ON c.id = n.campana_id
WHERE n.activo = TRUE;

-- ── FUNCIÓN: registrar nómina completa ──────────────────────
CREATE OR REPLACE FUNCTION registrar_nomina(p_data JSONB)
RETURNS UUID AS $$
DECLARE
  v_nomina_id UUID;
  v_doc VARCHAR(30);
BEGIN
  v_doc := p_data->>'documento';

  INSERT INTO postulantes (
    documento, tipo_documento, apellido_paterno, apellido_materno, nombres,
    celular, celular_referencia, correo, genero, fecha_nacimiento,
    estado_civil, n_hijos, nivel_academico, carrera, nacionalidad,
    lugar_residencia, distrito_residencia, direccion_domicilio, updated_at
  ) VALUES (
    v_doc,
    COALESCE(p_data->>'tipo_documento', 'DNI'),
    p_data->>'apellido_paterno',
    p_data->>'apellido_materno',
    p_data->>'nombres',
    p_data->>'celular',
    p_data->>'celular_referencia',
    p_data->>'correo',
    p_data->>'genero',
    (p_data->>'fecha_nacimiento')::DATE,
    p_data->>'estado_civil',
    COALESCE((p_data->>'n_hijos')::INTEGER, 0),
    p_data->>'nivel_academico',
    p_data->>'carrera',
    COALESCE(p_data->>'nacionalidad', 'PERUANA'),
    p_data->>'lugar_residencia',
    p_data->>'distrito_residencia',
    p_data->>'direccion_domicilio',
    NOW()
  )
  ON CONFLICT (documento) DO UPDATE SET
    tipo_documento = EXCLUDED.tipo_documento,
    apellido_paterno = EXCLUDED.apellido_paterno,
    apellido_materno = EXCLUDED.apellido_materno,
    nombres = EXCLUDED.nombres,
    celular = EXCLUDED.celular,
    celular_referencia = EXCLUDED.celular_referencia,
    correo = EXCLUDED.correo,
    genero = EXCLUDED.genero,
    fecha_nacimiento = EXCLUDED.fecha_nacimiento,
    estado_civil = EXCLUDED.estado_civil,
    n_hijos = EXCLUDED.n_hijos,
    nivel_academico = EXCLUDED.nivel_academico,
    carrera = EXCLUDED.carrera,
    nacionalidad = EXCLUDED.nacionalidad,
    lugar_residencia = EXCLUDED.lugar_residencia,
    distrito_residencia = EXCLUDED.distrito_residencia,
    direccion_domicilio = EXCLUDED.direccion_domicilio,
    updated_at = NOW();

  UPDATE nominas SET activo = FALSE, updated_at = NOW()
  WHERE postulante_documento = v_doc AND activo = TRUE;

  INSERT INTO nominas (
    postulante_documento, periodo_reclutado, semana_trabajo,
    reclutador_id, sede_id, campana_id,
    fuente_oferta, observacion_reclutamiento,
    exp_call_center, exp_tipo_campana, exp_tiempo_campana, exp_otra, exp_tiempo_otra,
    grupo_codigo, modalidad, condicion, horario_gestion, descanso,
    envio_dni, test_psicologico, validacion_pc, evaluacion_dia_0,
    fecha_inicio_capacitacion, fecha_fin_capacitacion,
    fecha_conexion_ojt, fecha_conexion_op, pago_capacitacion,
    tipo_contratacion, razon_social, remuneracion,
    bono_variable, bono_movilidad, bono_bienvenida, bono_permanencia, bono_asistencia_perfecta,
    cargo_contractual, dia_0, dia_0_obs, status_dia_1, dia_1, dia_1_obs,
    estado, activo
  ) VALUES (
    v_doc,
    p_data->>'periodo_reclutado',
    (p_data->>'semana_trabajo')::INTEGER,
    (p_data->>'reclutador_id')::BIGINT,
    (p_data->>'sede_id')::BIGINT,
    (p_data->>'campana_id')::BIGINT,
    p_data->>'fuente_oferta',
    p_data->>'observacion_reclutamiento',
    (p_data->>'exp_call_center')::BOOLEAN,
    p_data->>'exp_tipo_campana',
    p_data->>'exp_tiempo_campana',
    p_data->>'exp_otra',
    p_data->>'exp_tiempo_otra',
    p_data->>'grupo_codigo',
    (p_data->>'modalidad')::modalidad_tipo,
    p_data->>'condicion',
    p_data->>'horario_gestion',
    p_data->>'descanso',
    (p_data->>'envio_dni')::DATE,
    p_data->>'test_psicologico',
    p_data->>'validacion_pc',
    p_data->>'evaluacion_dia_0',
    (p_data->>'fecha_inicio_capacitacion')::DATE,
    (p_data->>'fecha_fin_capacitacion')::DATE,
    (p_data->>'fecha_conexion_ojt')::DATE,
    (p_data->>'fecha_conexion_op')::DATE,
    COALESCE((p_data->>'pago_capacitacion')::BOOLEAN, FALSE),
    p_data->>'tipo_contratacion',
    p_data->>'razon_social',
    (p_data->>'remuneracion')::NUMERIC,
    (p_data->>'bono_variable')::NUMERIC,
    (p_data->>'bono_movilidad')::NUMERIC,
    (p_data->>'bono_bienvenida')::NUMERIC,
    (p_data->>'bono_permanencia')::NUMERIC,
    (p_data->>'bono_asistencia_perfecta')::NUMERIC,
    p_data->>'cargo_contractual',
    (p_data->>'dia_0')::DATE,
    p_data->>'dia_0_obs',
    p_data->>'status_dia_1',
    (p_data->>'dia_1')::DATE,
    p_data->>'dia_1_obs',
    COALESCE((p_data->>'estado')::nomina_estado, 'RECLUTADO'),
    TRUE
  )
  RETURNING id INTO v_nomina_id;

  RETURN v_nomina_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

GRANT EXECUTE ON FUNCTION registrar_nomina(JSONB) TO authenticated;

-- ── AUDITORÍA AUTOMÁTICA ────────────────────────────────────
CREATE OR REPLACE FUNCTION procesar_auditoria()
RETURNS TRIGGER AS $$
DECLARE
  v_old JSONB; v_new JSONB; v_id VARCHAR(100); v_email VARCHAR(255);
  v_row JSONB;
BEGIN
  BEGIN
    v_email := COALESCE(current_setting('request.jwt.claim.email', true), 'system');
  EXCEPTION WHEN OTHERS THEN v_email := 'system'; END;

  IF TG_OP = 'DELETE' THEN
    v_old := to_jsonb(OLD);
    v_row := v_old;
  ELSIF TG_OP = 'UPDATE' THEN
    v_old := to_jsonb(OLD); v_new := to_jsonb(NEW);
    v_row := v_new;
  ELSE
    v_new := to_jsonb(NEW);
    v_row := v_new;
  END IF;

  v_id := COALESCE(
    v_row->>'documento',
    v_row->>'id',
    v_row->>'postulante_documento',
    v_row->>'nomina_id',
    'unknown'
  );

  INSERT INTO audit_logs(tabla_afectada, operacion, id_registro, valores_anteriores, valores_nuevos, usuario_email)
  VALUES (TG_TABLE_NAME, TG_OP, v_id, v_old, v_new, v_email);

  RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

DROP TRIGGER IF EXISTS audit_postulantes ON postulantes;
CREATE TRIGGER audit_postulantes AFTER INSERT OR UPDATE OR DELETE ON postulantes
  FOR EACH ROW EXECUTE FUNCTION procesar_auditoria();

DROP TRIGGER IF EXISTS audit_nominas ON nominas;
CREATE TRIGGER audit_nominas AFTER INSERT OR UPDATE OR DELETE ON nominas
  FOR EACH ROW EXECUTE FUNCTION procesar_auditoria();

DROP TRIGGER IF EXISTS audit_asistencias ON asistencias_capacitacion;
CREATE TRIGGER audit_asistencias AFTER INSERT OR UPDATE OR DELETE ON asistencias_capacitacion
  FOR EACH ROW EXECUTE FUNCTION procesar_auditoria();

-- ── RLS ─────────────────────────────────────────────────────
ALTER TABLE sedes ENABLE ROW LEVEL SECURITY;
ALTER TABLE campanas ENABLE ROW LEVEL SECURITY;
ALTER TABLE reclutadores ENABLE ROW LEVEL SECURITY;
ALTER TABLE postulantes ENABLE ROW LEVEL SECURITY;
ALTER TABLE nominas ENABLE ROW LEVEL SECURITY;
ALTER TABLE asistencias_capacitacion ENABLE ROW LEVEL SECURITY;
ALTER TABLE evaluaciones_capacitacion ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE grupos_capacitacion ENABLE ROW LEVEL SECURITY;
ALTER TABLE formadores ENABLE ROW LEVEL SECURITY;

-- Lectura general para autenticados
DO $$ DECLARE t TEXT;
BEGIN
  FOREACH t IN ARRAY ARRAY['sedes','campanas','reclutadores','postulantes','nominas',
    'asistencias_capacitacion','evaluaciones_capacitacion','grupos_capacitacion','formadores','audit_logs']
  LOOP
    EXECUTE format('DROP POLICY IF EXISTS select_all ON %I', t);
    EXECUTE format('CREATE POLICY select_all ON %I FOR SELECT TO authenticated USING (true)', t);
  END LOOP;
END $$;

-- Escritura postulantes/nominas: admin + reclutador
CREATE POLICY insert_postulantes ON postulantes FOR INSERT TO authenticated
  WITH CHECK (EXISTS (SELECT 1 FROM perfiles WHERE id = auth.uid() AND rol IN ('admin','reclutador')));

CREATE POLICY update_postulantes ON postulantes FOR UPDATE TO authenticated
  USING (EXISTS (SELECT 1 FROM perfiles WHERE id = auth.uid() AND rol IN ('admin','reclutador')));

CREATE POLICY insert_nominas ON nominas FOR INSERT TO authenticated
  WITH CHECK (EXISTS (SELECT 1 FROM perfiles WHERE id = auth.uid() AND rol IN ('admin','reclutador')));

CREATE POLICY update_nominas ON nominas FOR UPDATE TO authenticated
  USING (EXISTS (SELECT 1 FROM perfiles WHERE id = auth.uid() AND rol IN ('admin','reclutador','formador')));

-- Asistencias: admin + formador
CREATE POLICY write_asistencias ON asistencias_capacitacion FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM perfiles WHERE id = auth.uid() AND rol IN ('admin','formador')))
  WITH CHECK (EXISTS (SELECT 1 FROM perfiles WHERE id = auth.uid() AND rol IN ('admin','formador')));

-- Catálogos: admin y reclutador pueden crear (roleplay)
DROP POLICY IF EXISTS admin_sedes ON sedes;
DROP POLICY IF EXISTS admin_campanas ON campanas;
DROP POLICY IF EXISTS admin_reclutadores ON reclutadores;

CREATE POLICY write_sedes ON sedes FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM perfiles WHERE id = auth.uid() AND rol IN ('admin','reclutador')))
  WITH CHECK (EXISTS (SELECT 1 FROM perfiles WHERE id = auth.uid() AND rol IN ('admin','reclutador')));

CREATE POLICY write_campanas ON campanas FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM perfiles WHERE id = auth.uid() AND rol IN ('admin','reclutador','formador')))
  WITH CHECK (EXISTS (SELECT 1 FROM perfiles WHERE id = auth.uid() AND rol IN ('admin','reclutador','formador')));

CREATE POLICY write_grupos ON grupos_capacitacion FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM perfiles WHERE id = auth.uid() AND rol IN ('admin','formador')))
  WITH CHECK (EXISTS (SELECT 1 FROM perfiles WHERE id = auth.uid() AND rol IN ('admin','formador')));

CREATE POLICY write_formadores ON formadores FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM perfiles WHERE id = auth.uid() AND rol IN ('admin','formador')))
  WITH CHECK (EXISTS (SELECT 1 FROM perfiles WHERE id = auth.uid() AND rol IN ('admin','formador')));

CREATE POLICY write_reclutadores ON reclutadores FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM perfiles WHERE id = auth.uid() AND rol IN ('admin','reclutador')))
  WITH CHECK (EXISTS (SELECT 1 FROM perfiles WHERE id = auth.uid() AND rol IN ('admin','reclutador')));

-- Perfiles (mantener existente)
DROP POLICY IF EXISTS select_perfiles ON perfiles;
DROP POLICY IF EXISTS insert_perfiles ON perfiles;
DROP POLICY IF EXISTS update_perfiles ON perfiles;

CREATE POLICY select_perfiles ON perfiles FOR SELECT TO authenticated USING (true);
CREATE POLICY insert_perfiles ON perfiles FOR INSERT WITH CHECK (true);
CREATE POLICY update_perfiles ON perfiles FOR UPDATE TO authenticated
  USING (auth.uid() = id OR EXISTS (SELECT 1 FROM perfiles p WHERE p.id = auth.uid() AND p.rol = 'admin'))
  WITH CHECK (auth.uid() = id OR EXISTS (SELECT 1 FROM perfiles p WHERE p.id = auth.uid() AND p.rol = 'admin'));

-- get_my_profile (auth)
CREATE OR REPLACE FUNCTION get_my_profile()
RETURNS perfiles AS $$
DECLARE result perfiles; v_meta JSONB; v_rol TEXT;
BEGIN
  SELECT * INTO result FROM perfiles WHERE id = auth.uid();
  IF FOUND THEN RETURN result; END IF;
  v_meta := COALESCE(auth.jwt()->'user_metadata', '{}'::jsonb);
  v_rol := v_meta->>'rol';
  INSERT INTO perfiles (id, nombre, rol) VALUES (
    auth.uid(),
    COALESCE(v_meta->>'nombre', split_part(COALESCE(auth.jwt()->>'email',''), '@', 1), 'Usuario'),
    CASE WHEN v_rol IN ('admin','reclutador','formador','visor') THEN v_rol::app_role ELSE 'visor'::app_role END
  ) ON CONFLICT (id) DO NOTHING RETURNING * INTO result;
  IF NOT FOUND THEN SELECT * INTO result FROM perfiles WHERE id = auth.uid(); END IF;
  RETURN result;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;
GRANT EXECUTE ON FUNCTION get_my_profile() TO authenticated;
